name: Check code quality and tests
description: Composite action to check code quality using eslint and to check tests ine the app

runs:
  using: 'composite'
  steps:
    - name: Lint code
      run: npm run lint
      shell: bash

    - name: Run unit tests
      run: npm run test
      shell: bash